Repository JupiterBroadcasting/jupiterbroadcasting.com, pull requests merged in 2022-09, with the labels that each got.

#366 should deploy website now after scraper commits
  .github/workflows/deploy-prod.yml
Labels: bug

#370 E2E - update Live menu item check address
  test/conftest.py
Labels: duplicate

#369 GH workflow - remove redundant `git fetch`
  .github/workflows/deploy-prod.yml
Labels: low priority

#399 disable Archive menu item temporarily
  config.toml
Labels: bug

#396 :technologist: makefile - add `dev-build-metrics`: hugo build metrics reporting
  Makefile
Labels: dev, piece of :cake:

#413 E2E - fixing failing Archive nav test that's currently failing
  test/conftest.py
Labels: urgent, piece of :cake:

#407 Show Icon Updates
  content/show/coder-radio/_index.md
  content/show/linux-action-news/_index.md
  content/show/linux-unplugged/_index.md
  content/show/self-hosted/_index.md
  themes/jb/layouts/partials/show/links.html
Labels: piece of :cake:

#346 add Subscribe button to Episode pages
  content/show/linux-unplugged/_index.md
  content/show/office-hours/_index.md
  themes/jb/layouts/episode/single.html
  themes/jb/layouts/partials/episode/subscribe.html
Labels: design, urgent, in progress

#428 Bug/issue templates - typo, formatting, grammar massaging
  .github/ISSUE_TEMPLATE/bug_shownotes.yml
  .github/ISSUE_TEMPLATE/bug_website.yml
  .github/ISSUE_TEMPLATE/dev.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: low priority, piece of :cake:

#427 Add 404 page
  Dockerfile
  themes/jb/layouts/404.html
Labels: in progress
