Repository JupiterBroadcasting/jupiterbroadcasting.com, pull requests merged in 2022-10, with the labels that each got.

#447 update sponsorship info
  content/sponsors/_index.md
Labels: piece of :cake:

#454 synchronizing main (for deployment)
  content/sponsors/_index.md
  themes/jb/layouts/_default/single.html
Labels: enhancement, piece of :cake:

#449 Improve Accessibility
  config.toml
  themes/jb/layouts/_default/baseof.html
  themes/jb/layouts/index.html
  themes/jb/layouts/partials/footer.html
  themes/jb/layouts/partials/header.html
Labels: piece of :cake:

#446 Render Full Contact Form even when there are Validation Errors
  test/e2e/test_contact.py
  themes/jb/layouts/contact/single.html
Labels: design, QA

#452 Add Subscribe and Support on Show Page
  content/show/coder-radio/_index.md
  content/show/jupiter-extras/_index.md
  content/show/linux-action-news/_index.md
  content/show/linux-unplugged/_index.md
  content/show/office-hours/_index.md
  content/show/self-hosted/_index.md
  themes/jb/layouts/partials/episode/subscribe.html
  themes/jb/layouts/partials/episode/support.html
  themes/jb/layouts/partials/show/links.html
  themes/jb/layouts/show/list.html
Labels: enhancement, design, UX

#460 synchronizing main (for deployment)
  .github/ISSUE_TEMPLATE/bug_shownotes.yml
  .github/ISSUE_TEMPLATE/bug_website.yml
  .github/ISSUE_TEMPLATE/dev.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  content/show/coder-radio/_index.md
  content/show/jupiter-extras/_index.md
  content/show/linux-action-news/_index.md
  content/show/linux-unplugged/_index.md
  content/show/office-hours/_index.md
  content/show/self-hosted/_index.md
  test/e2e/test_contact.py
  themes/jb/layouts/contact/single.html
  themes/jb/layouts/partials/episode/subscribe.html
  themes/jb/layouts/partials/episode/support.html
  themes/jb/layouts/partials/show/links.html
  themes/jb/layouts/show/list.html
Labels: enhancement, QA, deployment

#464 This increases the heading size of topic in footer
  themes/jb/layouts/partials/footer.html
Labels: design, piece of :cake:, hacktoberfest

#456 Deploy Previews and URL Encoding Tags
  README.md
  config.toml
  render.yaml
  themes/jb/layouts/partials/episode/tags.html
Labels: enhancement, JB - action needed, infrastructure

#353 E2E GH Action - patch/modifying
  .dockerignore
  .github/workflows/build_container-prod.yml
  .github/workflows/build_container-tests.yml
  .github/workflows/build_containers.md
  .github/workflows/deploy-prod.yml
  .github/workflows/e2e.yml
  Dockerfile
  Dockerfile.tests
  Makefile
  pytest.ini
  test/Pipfile
  test/Pipfile.lock
  test/conftest.py
  test/docker-compose.yml
  test/e2e/test_home.py
  test/e2e/test_infra_configs.py
  test/requirements.txt
Labels: urgent, in progress, feedback requested, dev

#451 Feature/automate sponsors page
  config.toml
  config/_default/params.toml
  content/show/self-hosted/_index.md
  content/sponsors/_index.md
  content/sponsors/linode.com-jb.md
  themes/jb/layouts/partials/sponsor/medium.html
  themes/jb/layouts/sponsors/list.html
Labels: JB - need decision, JB - action needed

#472 synchronizing main (for deployment)
  .dockerignore
  .github/workflows/build_container-prod.yml
  .github/workflows/build_container-tests.yml
  .github/workflows/build_containers.md
  .github/workflows/deploy-prod.yml
  .github/workflows/e2e.yml
  .gitignore
  CONTRIBUTING.md
  Dockerfile
  Dockerfile.tests
  Makefile
  README.md
  config.toml
  config/_default/params.toml
  content/show/self-hosted/_index.md
  content/sponsors/_index.md
  content/sponsors/linode.com-jb.md
  pytest.ini
  render.yaml
  test/Pipfile
  test/Pipfile.lock
  test/conftest.py
  test/docker-compose.yml
  test/e2e/test_home.py
  test/e2e/test_infra_configs.py
  test/requirements.txt
  themes/jb/layouts/partials/episode/tags.html
  themes/jb/layouts/partials/footer.html
  themes/jb/layouts/partials/sponsor/medium.html
  themes/jb/layouts/sponsors/list.html
Labels: enhancement, design, UX, piece of :cake:, QA

#463 Add the show name to the episode page titles
  themes/jb/layouts/partials/meta.html
Labels: piece of :cake:, hacktoberfest, hacktoberfest-accepted

#467 Improvements to makefile: help system and minor tweaks
  Makefile
Labels: feedback requested, dev
