Repository JupiterBroadcasting/jupiterbroadcasting.com, pull requests merged in 2022-08, with the labels that each got.

#214 :bug: Bug/community page n menu links/195
  themes/jb/layouts/partials/community/card.html
  themes/jb/layouts/partials/footer.html
  themes/jb/layouts/partials/header.html
Labels: bug

#298 [people] update danjohansen.md
  content/people/danjohansen.md
Labels: feedback requested

#290 fixing the warnings that show during deployment
  config.toml
Labels: bug

#321 Embed Kiwi next client
  themes/jb/layouts/partials/live/irc.html
Labels: enhancement, design, feedback requested

#325 Setup End to End Tests
  .github/workflows/e2e.yml
  .gitignore
  Dockerfile.tests
  Makefile
  pytest.ini
  test/Pipfile
  test/Pipfile.lock
  test/Readme.md
  test/conftest.py
  test/e2e/test_home.py
  test/requirements.txt
Labels: enhancement
