Repository JupiterBroadcasting/jupiterbroadcasting.com, pull requests merged in 2023-02, with the labels that each got.

#502 Temp Fix for Contact Page
  themes/jb/layouts/contact/single.html
Labels: third-party site, design, UX, piece of :cake:

#483 updating hugo to latest version (v0.105.0)
  Dockerfile
  Dockerfile.dev
Labels: enhancement, dev, infrastructure, QA, deployment

#493 Adding tests for live page
  test/conftest.py
  test/e2e/test_home.py
  test/e2e/test_live.py
  test/fixture_files/jb-live_sample-live-event.json
Labels: QA

#498 Opening external links in new tab
  themes/jb/layouts/_default/_markup/render-link.html
  themes/jb/layouts/partials/sponsor/medium.html
Labels: enhancement
