Repository JupiterBroadcasting/jupiterbroadcasting.com, pull requests merged in 2024-01, with the labels that each got.

#499 Adding standard favicon and svg favicon for theme support
  static/images/favicon/android-chrome-192x192.png
  static/images/favicon/android-chrome-512x512.png
  static/images/favicon/apple-touch-icon.png
  static/images/favicon/browserconfig.xml
  static/images/favicon/favicon-16x16.png
  static/images/favicon/favicon-32x32.png
  static/images/favicon/favicon-48x48.png
  static/images/favicon/favicon.ico
  static/images/favicon/favicon.svg
  static/images/favicon/mstile-150x150.png
  static/images/favicon/safari-pinned-tab.svg
  static/images/favicon/site.webmanifest
  themes/jb/layouts/partials/meta.html
Labels: design, low priority

#553 Add missing direct download links to back catalog
  content/show/coder-radio/0476.md
  content/show/coder-radio/0477.md
  content/show/coder-radio/0478.md
  content/show/coder-radio/0479.md
  content/show/coder-radio/0480.md
  content/show/jupiter-extras/0022.md
  content/show/jupiter-extras/0083.md
  content/show/jupiter-extras/0084.md
  content/show/jupiter-extras/0085.md
  content/show/jupiter-extras/0086.md
  content/show/jupiter-extras/0087.md
  content/show/linux-action-news/0251.md
  content/show/linux-action-news/0252.md
  content/show/linux-action-news/0253.md
  content/show/linux-action-news/0254.md
  content/show/linux-action-news/0255.md
  content/show/linux-unplugged/0469.md
  content/show/linux-unplugged/0470.md
  content/show/linux-unplugged/0471.md
  content/show/linux-unplugged/0472.md
  content/show/linux-unplugged/0473.md
  content/show/office-hours/0006.md
  content/show/office-hours/0007.md
  content/show/office-hours/0008.md
  content/show/office-hours/0009.md
  content/show/office-hours/0010.md
  content/show/self-hosted/0074.md
  content/show/self-hosted/0075.md
  content/show/self-hosted/0076.md
  content/show/self-hosted/0077.md
  content/show/self-hosted/0078.md
Labels: show notes

#563 Page People, filter is_archived hosts, mobile improvements
  content/people/friends.md
  themes/jb/layouts/partials/people/horizontal.html
  themes/jb/layouts/people/list.html
  themes/jb/layouts/taxonomy/guest.html
  themes/jb/layouts/taxonomy/host.html
Labels: design, UX

#568 Feature/add cr episodes 0 54
  content/show/coder-radio/0000.md
  content/show/coder-radio/0001.md
  content/show/coder-radio/0002.md
  content/show/coder-radio/0003.md
  content/show/coder-radio/0004.md
  content/show/coder-radio/0005.md
  content/show/coder-radio/0006.md
  content/show/coder-radio/0007.md
  content/show/coder-radio/0008.md
  content/show/coder-radio/0009.md
  content/show/coder-radio/0010.md
  content/show/coder-radio/0011.md
  content/show/coder-radio/0012.md
  content/show/coder-radio/0013.md
  content/show/coder-radio/0014.md
  content/show/coder-radio/0015.md
  content/show/coder-radio/0016.md
  content/show/coder-radio/0017.md
  content/show/coder-radio/0018.md
  content/show/coder-radio/0019.md
  content/show/coder-radio/0020.md
  content/show/coder-radio/0021.md
  content/show/coder-radio/0022.md
  content/show/coder-radio/0023.md
  content/show/coder-radio/0024.md
  content/show/coder-radio/0025.md
  content/show/coder-radio/0026.md
  content/show/coder-radio/0027.md
  content/show/coder-radio/0028.md
  content/show/coder-radio/0029.md
  content/show/coder-radio/0030.md
  content/show/coder-radio/0031.md
  content/show/coder-radio/0032.md
  content/show/coder-radio/0033.md
  content/show/coder-radio/0034.md
  content/show/coder-radio/0035.md
  content/show/coder-radio/0036.md
  content/show/coder-radio/0037.md
  content/show/coder-radio/0038.md
  content/show/coder-radio/0039.md
  content/show/coder-radio/0040.md
  content/show/coder-radio/0041.md
  content/show/coder-radio/0042.md
  content/show/coder-radio/0043.md
  content/show/coder-radio/0044.md
  content/show/coder-radio/0045.md
  content/show/coder-radio/0046.md
  content/show/coder-radio/0047.md
  content/show/coder-radio/0048.md
  content/show/coder-radio/0049.md
  content/show/coder-radio/0050.md
  content/show/coder-radio/0051.md
  content/show/coder-radio/0052.md
  content/show/coder-radio/0053.md
  content/show/coder-radio/0054.md
  static/images/misc/Techsnap100shirtFront.jpg
  themes/jb/layouts/episode/single.html
Labels: show notes, JB - need information

#572 Restore Host and Guest Lists
  themes/jb/layouts/tags/terms.html
Labels: urgent, UX

#564 Push footer to the bottom of page
  themes/jb/assets/css/main.sass
Labels: design, low priority
